highlighter: rouge

gems:
    - jekyll-textile-converter

exclude: [
    citationhunt/google/slides.md,
    citationhunt/google/reveal.js/css/theme/README.md,
    citationhunt/wikicite2017/slides.md,
    citationhunt/wikicite2017/reveal.js/css/theme/README.md,
]

markdown: kramdown
